### PR TITLE
yay I added my name and added twitter handle

### PR DESCRIPTION
**Pull request by maheshmnj**
this commit completes my first lesson to contribution to open source today

### CODE REVIEW

**Comment by catalinpit** [comment]
Hey, 

Please resolve the conflicts!

**Comment by maheshmnj** [comment]
hello @catalinpit  can you please help understand whats the conflict and how do I resolve it

**Comment by maheshmnj** [comment]
I think it should be resolved now probably by the time I  forked and made a pull request few people committed changes to the repo that way my repo was not in sync with the remote master branch which caused conflicts @catalinpit  please correct me if I am wrong

**Comment by catalinpit** [comment]
Yes. You are right. Well done!

**Pull request merged**
