### PR TITLE
Corrected a typo in the README

### PR DESCRIPTION
**Pull request by tochukwuali**
I think you meant to say 'Fork' in that first correction. For the second one, felt like 'in' sounded better than 'into'. Cheers!

### CODE REVIEW

**Comment by catalinpit** [comment]
In your sounds better in my opinion. Please, don't change that.

Thanks for the other additions!

**Comment by tochukwuali** [comment]
alright, thanks for the lesson. I've made my first OS contribution.

**Comment by catalinpit** [comment]
Only change the fork word please, not the others. Thank you!

**Comment by catalinpit** [comment]
Well done!

**Pull request merged**
